import { Character } from "@/types/character";

export const CHARACTERS: Character[] = [
    { id: 1, name: '랜덤', img: null},
    { id: 2, name: '니나', img: null},
    { id: 3, name: '데빌', img: null},
    { id: 4, name: '드라그노프', img: null},
    { id: 5, name: '라스', img: null},
    { id: 6, name: '레오', img: null},
    { id: 7, name: '레이나', img: null},
    { id: 8, name: '레이븐', img: null},
    { id: 9, name: '로우', img: null},
    { id: 10, name: '리', img: null},
    { id: 11, name: '리디아', img: null},
    { id: 12, name: '리로이', img: null},
    { id: 13, name: '리리', img: null},
    { id: 14, name: '브라이언', img: null},
    { id: 15, name: '빅터', img: null},
    { id: 16, name: '샤오유', img: null},
    { id: 17, name: '샤힌', img: null},
    { id: 18, name: '스티브', img: null},
    { id: 19, name: '아수세나', img: null},
    { id: 20, name: '아스카', img: null},
    { id: 21, name: '알리사', img: null},
    { id: 22, name: '에디', img: null},
    { id: 23, name: '요시미츠', img: null},
    { id: 24, name: '자피나', img: null},
    { id: 25, name: '잭8', img: null},
    { id: 26, name: '준', img: null},
    { id: 27, name: '진', img: null},
    { id: 28, name: '카즈야', img: null},
    { id: 29, name: '쿠마', img: null},
    { id: 30, name: '클라우디오', img: null},
    { id: 31, name: '클라이브', img: null},
    { id: 32, name: '킹', img: null},
    { id: 33, name: '펜더', img: null},
    { id: 34, name: '펭', img: null},
    { id: 35, name: '폴', img: null},
    { id: 36, name: '헤이하치', img: null},
    { id: 37, name: '화랑', img: null},
] as const;